version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"

sphinx:
   configuration: docs/src/conf.py

python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .
