sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install -r requirements
  - pip install wheel --upgrade
  - pip install .[test]
script:
  - python -m pytest --cov affine --cov-report term-missing
  - python -m pydocstyle affine
after_success:
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: seang
