dist: xenial
language: python
cache: pip
python:
  - 2.7
  - 3.6
  - 3.7
  - pypy3
install:
  - pip install flake8 pydocstyle
  - pip install .[test]
script:
  - flake8
  - python -m pydocstyle affine
  - python -m pytest --cov affine --cov-report term-missing
after_success:
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: __token__
